### ISSUE TITLE
How to integrate with pm2

### ISSUE THREAD

**Issue by vishalbiradar** [nearform/node-clinic#233]
I am using pm2 and I want to integrate all three doctor, flame, bubbleprof with my current nodejs app.

I am unable to add the clinic js command to my script:  

**package.json file**

```
"main": "app.js",
  "scripts": {
    "start": "node setEnv.js && pm2 start process.json",
}
```
The setEnv.js will set the details to process.json file. The json file contains the details required for pm2 to start the application.

**process.json**

```
{
    "apps" : [{
        "name": "mgmt_server",
        "script": "app.js",
        "instances": 1,
        "watch": false
      }]
    }
```

## Environment
* Clinic.js version: v5.0.1
* Node.js version: v10.13.0

**Comment by DylanC** [comment]
@vishalbiradar - This looks to be a dup of #96. Web workers are not supported at the moment.

**Comment by vishalbiradar** [comment]
@DylanC 
It's different than https://github.com/nearform/node-clinic/issues/96

My issue is, how to integrate with pm2 and how to run all them together doctor, flame, bubbleprof instead of running them separately.

**Comment by goto-bus-stop** [comment]
The tools all inject code into your app to do the profiling. You can't run both doctor and flame at the same time for example—even if you could, the data would be bad because the profiling code could interfere with the performance.

pm2 is intended for running apps over a long period of time. The Clinic.js tools are not suitable for that. They generate lots of profiling data, and processing and visualizing all that data becomes infeasible even after just a few minutes. Typically, Clinic.js tools are run for only 10 or 20 seconds at a time.

Instead, you should run smaller benchmarks using the `app.js` directly:
```
clinic doctor --autocannon [ /endpoint/to/benchmark ] -- node app.js
```

**Comment by vishalbiradar** [comment]
@goto-bus-stop @DylanC 
Thanks...

One broader question...
Where (in dev or production or both) and when we must use profiling?
If I am having 50 plus developed rest APIs as part of node js. Then how can we perform the profiling?

Actually I am not understanding when, where, and why to use profiling?
