### ISSUE TITLE
File should be clickable

### ISSUE THREAD

**Issue by BridgeAR** [nearform/node-clinic#82]
Example: `Generated HTML file is 15703.clinic-flame.html`

Here the filename is not referenced as `file://...` and can not be clicked upon on the terminal.

**Comment by DylanC** [comment]
@goto-bus-stop - I had a little play around with the code but nothing to show for this yet. How would we approach this one?

**Comment by goto-bus-stop** [comment]
@DylanC This line:
https://github.com/nearform/node-clinic/blob/52125ec14923ebd278c5c5d733dc1005d5e339d0/bin.js#L597
should use the absolute path to the file and print `file://${absolutePath}` instead of only the `.clinic` path. You can use the [path.resolve](https://nodejs.org/api/path.html#path_path_resolve_paths) API to turn the relative path into an absolute path.

**Comment by DylanC** [comment]
@goto-bus-stop - That's the line I was playing around with already. However, I didn't try adjusting the path to be absolute. (which is probably the missing piece here)

**Comment by DylanC** [comment]
@BridgeAR - Fix pushed to master for this issue.
